sudo: required
services:
  - docker

before_install:
  - docker build -t triphamtran/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true triphamtran/docker-react npm run test -- --watchAll=false

